### PR TITLE
[event_parser.rb] Filter out extra_vars data

### PR DESCRIPTION
**Pull request by NickLaMuro**
This is an alternative to https://github.com/ManageIQ/manageiq/pull/19308

Since we can't be sure if there is sensitive data in there, it is better to just filter this out in the logs.  Hopefully this data isn't being used anywhere when parsing `job_create` events...

### CODE REVIEW

**Comment by Fryguy** [comment]
cc @dmetzger57 @tinaafitz

**Comment by Fryguy** [comment]
Note that if we backport this, we *may* need a second identical fix to the old tower-based embedded ansible.

**Comment by NickLaMuro** [comment]
@Fryguy Yes, we would need a `hammer`  specific one, but that would only be making the same change in what used to be the `app/models/manageiq/providers/ansible-tower/shared` directory.  There shouldn't have to be a core PR for `hammer`.

**Comment by NickLaMuro** [comment]
@miq-bot remove label hammer/yes

Hammer is being backported here:  https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/194

**Comment by NickLaMuro** [comment]
bah...

@miq-bot remove_label hammer/yes

**Comment by simaishi** [comment]
Backported to hammer via https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/194

**Comment by simaishi** [comment]
@NickLaMuro backporting to `ivanchuk` conflicts as it's using shared parser, maybe same conflict as hammer... anyway, please create a separate PR for ivanchuk branch.

**Comment by NickLaMuro** [comment]
@simaishi I created a ivanchuk branch and assigned you that PR.  Let me know if you need anything else.  Thanks!

**Pull request merged**
