### PR TITLE
Tower Rhv credential type

### PR DESCRIPTION
**Pull request by jameswnl**
https://bugzilla.redhat.com/show_bug.cgi?id=1526048

@miq-bot add_lables wip, enhancements

### CODE REVIEW

**Comment by jameswnl** [comment]
@miq-bot remove_label wip
@miq-bot add_label enhancement

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit ee546a0b729c6167fa46df9b5496f55f4ed181f0
Author: Adam Grare <agrare@redhat.com>
Date:   Tue Mar 13 09:01:01 2018 -0400

    Merge pull request #62 from jameswnl/rhev
    
    Tower Rhv credential type
    (cherry picked from commit fdc757d48f258876a28d38cfd6872e8ae6d8543f)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1559479
```

**Pull request merged**
