### PR TITLE
Add missing VCR Cassettes

### PR DESCRIPTION
**Pull request by juliancheal**

### CODE REVIEW

**Comment by juliancheal** [comment]
Closing PR after gitter discussion to keep VCR cassettes in main ManageIQ repo for now, as they are shared by Embedded Ansible.

**Comment by juliancheal** [comment]
@miq-bot assign @bronaghs

**Comment by bronaghs** [comment]
@juliancheal - Why was this reopened? I see it was closed deliberately after a gitter discussion.

**Comment by juliancheal** [comment]
> @juliancheal - Why was this reopened? I see it was closed deliberately after a gitter discussion.

After another conversation it was decided the cassettes should live in this repo https://gitter.im/ManageIQ/manageiq-providers-ansible_tower?at=594187e1cf9c13503c874006

**Pull request merged**
