### PR TITLE
[Changelog] Update for Ivanchuk Beta1

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by simaishi** [comment]
@JPrause Not sure why we didn't have changelog for some Sprints, like 110. Please take a look.

**Comment by agrare** [comment]
@simaishi there weren't any PRs merged to this repo in Sprint 110

**Comment by simaishi** [comment]
https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/136 (Sprint 110)https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/170 (Sprint 111)

**Comment by JPrause** [comment]
I'm sure if we looked hard enough, there's probably a missed PR for every repo. This happens sometimes when the Milestone isn't set at the time the report is run. Not sure there's a need to go back and verify more than the last sprint. However, if you feel strongly enough, I will add these two PRs.

**Comment by simaishi** [comment]
@JPrause This should not be about if we need to add a PR or two now, but should be about improving the process to catch those. I mention some of those missing PRs (not all), so you can check what happened.  And I do avoid mentioning PRs without milestone, for example. 

Anyway, let's discuss offline.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit fef041c3ea971898025d038781af052e8276f2db
Author: Adam Grare <agrare@redhat.com>
Date:   Fri Jul 26 13:43:23 2019 -0400

    Merge pull request #179 from JPrause/ivanb1_cl
    
    [Changelog] Update for Ivanchuk Beta1
    
    (cherry picked from commit 88aa135c1acd6146a17d01ad5ecbf65540c5890f)
```

**Pull request merged**
